<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-04 at 03:07:14.
 */
class bkf_RequestTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var bkf_Request
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new bkf_Request;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	/**
	 * @covers bkf_Request::__get
	 * @todo   Implement test__get().
	 */
	public function test__get() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers bkf_Request::parseUri
	 * @todo   Implement testParseUri().
	 */
	public function testParseUri() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers bkf_Request::getParam
	 * @todo   Implement testGetParam().
	 */
	public function testGetParam() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers bkf_Request::setParam
	 * @todo   Implement testSetParam().
	 */
	public function testSetParam() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers bkf_Request::parseParams
	 * @todo   Implement testParseParams().
	 */
	public function testParseParams() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers bkf_Request::getAction
	 * @todo   Implement testGetAction().
	 */
	public function testGetAction() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers bkf_Request::getElement
	 * @todo   Implement testGetElement().
	 */
	public function testGetElement() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers bkf_Request::getMethod
	 * @todo   Implement testGetMethod().
	 */
	public function testGetMethod() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
