<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-04 at 03:07:13.
 */
class bkf_ResponseTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var bkf_Response
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new bkf_Response;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	/**
	 * @covers bkf_Response::getCode
	 * @todo   Implement testGetCode().
	 */
	public function testGetCode() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers bkf_Response::getStatus
	 * @todo   Implement testGetStatus().
	 */
	public function testGetStatus() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers bkf_Response::getContentType
	 * @todo   Implement testGetContentType().
	 */
	public function testGetContentType() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers bkf_Response::getCharset
	 * @todo   Implement testGetCharset().
	 */
	public function testGetCharset() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers bkf_Response::getType
	 * @todo   Implement testGetType().
	 */
	public function testGetType() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers bkf_Response::getContents
	 * @todo   Implement testGetContents().
	 */
	public function testGetContents() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers bkf_Response::setCode
	 * @todo   Implement testSetCode().
	 */
	public function testSetCode() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers bkf_Response::setStatus
	 * @todo   Implement testSetStatus().
	 */
	public function testSetStatus() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers bkf_Response::setContentType
	 * @todo   Implement testSetContentType().
	 */
	public function testSetContentType() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers bkf_Response::setCharset
	 * @todo   Implement testSetCharset().
	 */
	public function testSetCharset() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers bkf_Response::setType
	 * @todo   Implement testSetType().
	 */
	public function testSetType() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers bkf_Response::setContents
	 * @todo   Implement testSetContents().
	 */
	public function testSetContents() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
