<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-04 at 03:07:13.
 */
class bkf_ConfigTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var bkf_Config
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new bkf_Config;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	/**
	 * @covers bkf_Config::getInstance
	 * @todo   Implement testGetInstance().
	 */
	public function testGetInstance() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers bkf_Config::__get
	 * @todo   Implement test__get().
	 */
	public function test__get() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers bkf_Config::__set
	 * @todo   Implement test__set().
	 */
	public function test__set() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers bkf_Config::get
	 * @todo   Implement testGet().
	 */
	public function testGet() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers bkf_Config::set
	 * @todo   Implement testSet().
	 */
	public function testSet() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
